### PR TITLE
DEV-10224 replace moment

### PR DESCRIPTION
**Pull request by nick-torres**
**High level description:**

replace moment with dayjs

**JIRA Ticket:**
[DEV-10224](https://federal-spending-transparency.atlassian.net/browse/DEV-10224)

The following are ALL required for the PR to be merged:

Author:
- [x] Linked to this PR in JIRA ticket
- [ ] Scheduled demo including Design/Testing/Front-end OR Provided instructions for testing in JIRA and PR `if applicable`
- [ ] Verified cross-browser compatibility: Chrome, Safari, Firefox, Edge
- [ ] Verified mobile/tablet/desktop/monitor responsiveness
- [ ] Verified that this PR does not create any *new* accessibility issues (via Axe Chrome extension)
- [ ] Added Unit Tests for helper functions, reducers, models and Container/Component Interactivity Expectations `if applicable` [React Testing Library](react-testing-library.md)
- [ ] [API contract](https://github.com/fedspendingtransparency/usaspending-api/tree/dev/usaspending_api/api_contracts) updated `if applicable`
- [ ] [Component Library Integration Status Report](https://github.com/fedspendingtransparency/data-act-documentation/blob/data-transparency-ui/frontend_apps/component-library-integration-status.md) updated `if applicable`

Reviewer(s):
- [ ] Design review complete `if applicable`
- [ ] [API #1234](https://github.com/fedspendingtransparency/usaspending-api/pull/1234) merged concurrently `if applicable`
- [ ] Code review complete

### CODE REVIEW

**Comment by nick-torres** [comment]
had to go down a rabbit hole with this one, so whoever reviews it hit me up before you do and i'll summarize it on a call for you

**Comment by brianpetway** [comment]
A function called getLatestPeriodAsMoment is imported and still called in WithLatestFy.jsx and DateNote.jsx. These files also use an object called latestMoment. You changed the name of the getLatestPeriodAsMoment function in accountHelper.js to getLatestPeriodAsdayjs. So you need to change the old function calls to the new name.
This is causing the homepage to break.

Award pages are throwing an error that says dayjs.duration is not a function. Apparently the .duration method was included in Moment but has to be added in dayjs as a plugin.
https://stackoverflow.com/questions/76429668/moving-moment-to-dayjs-in-react

It looks like that .duration is called in timeRangeHelper.js.

**Comment by brianpetway** [comment]
WithLatestFy.jsx has two var names that still use Moment - latestMoment and latestPeriodAsMoment - we should change these to be less confusing for future devs, since we're no longer using Moment.

And AC3 says to leave some guidance for QA on what to test. I know a lot of files were changed and the effects are pretty broad, but we should give her something to go on for this ticket.

**Review by brianpetway — APPROVED** [review]
