### PR TITLE
DEV-8976 fixed xxx is not a function test

### PR DESCRIPTION
**Pull request by nick-torres**
**High level description:**

fixed error with jest tests
**Technical details:**

a function was not mocked when it should have been

**JIRA Ticket:**
[DEV-8976](https://federal-spending-transparency.atlassian.net/browse/DEV-8976)

The following are ALL required for the PR to be merged:

Author:
- [x] Linked to this PR in JIRA ticket
- [ ] Scheduled demo including Design/Testing/Front-end OR Provided instructions for testing in JIRA and PR `if applicable`
- [ ] Verified cross-browser compatibility: Chrome, Safari, Firefox, Edge
- [ ] Verified mobile/tablet/desktop/monitor responsiveness
- [ ] Verified that this PR does not create any *new* accessibility issues (via Axe Chrome extension)
- [ ] Added Unit Tests for helper functions, reducers, models and Container/Component Interactivity Expectations `if applicable` [React Testing Library](react-testing-library.md)
- [ ] [API contract](https://github.com/fedspendingtransparency/usaspending-api/tree/dev/usaspending_api/api_contracts) updated `if applicable`
- [ ] [Component Library Integration Status Report](https://github.com/fedspendingtransparency/data-act-documentation/blob/data-transparency-ui/frontend_apps/component-library-integration-status.md) updated `if applicable`

Reviewer(s):
- [ ] Design review complete `if applicable`
- [ ] [API #1234](https://github.com/fedspendingtransparency/usaspending-api/pull/1234) merged concurrently `if applicable`
- [ ] Code review complete

### CODE REVIEW

**Review by anjenkin — CHANGES_REQUESTED** [review]
A comment and question inline - 
1) Are you getting this error when running this branch locally?
ERROR in ./index.js
Module build failed: Error: Keyword [object Object] is not a valid identifier
    at Ajv.addKeyword (/Users/andreablackwell/code/usaspending-website/node_modules/babel-loader/node_modules/ajv/lib/keyword.js:30:11)

2) Is this ticket ready to merge?  It's marked as ready for review but still has the do not merge label

File: tests/containers/award/idv/IdvActivityContainer-test.jsx [hunk 1]
```diff
@@ -105,9 +112,20 @@ xdescribe('IdvActivityContainer', () => {
         expect(container.state().awards.length).toEqual(awards.length - 1);
     });
 
-    it('should change the page and update state and call api', () => {
-        const container = shallow(<IdvActivityContainer awardId="1234" />);
```
[the remark this answers is not in the document]
Comment (nick-torres) [reply tests/containers/award/idv/IdvActivityContainer-test.jsx:109]: the first test failed and didn't use shallow if i remember correctly so i don't think it was that

[the remark this answers is not in the document]
Comment (nick-torres) [reply tests/containers/award/idv/IdvActivityContainer-test.jsx:109]: misread - i don't know if changing it from shallow made a difference, i tried to make it look like the first test i can't remember if it was still failing after i got the first test to pass

**Review by anjenkin — APPROVED** [review]
